(function() {
  'use strict';
  angular
    .module('ng-neer',[
      'ngRoute'
    ])
    .controller("HomeController", function($scope) {

      $scope._Index = 0;


      $scope.isActive = function (index) {
          return $scope._Index === index;
      };

      $scope.showPrev = function () {
          $scope._Index = ($scope._Index > 0) ? --$scope._Index : $scope.photos.length - 1;
      };

      $scope.showNext = function () {
          $scope._Index = ($scope._Index < $scope.photos.length - 1) ? ++$scope._Index : 0;
      };

      $scope.showPhoto = function (index) {
          $scope._Index = index;
      };

      $scope.notes = false;

      $scope.currentLink = "Notes";
      $scope.toggleNotes = function() {
        $scope.notes = !$scope.notes;
        if($scope.currentLink === "Notes") {
          $scope.currentLink = "Photos";
        } else {
          $scope.currentLink = "Notes";
        }
      }

      $scope.photos = [

         {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/10355566_10203329758981185_3640802450216897793_o.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/10460839_10203329761301243_3225320073784677972_o.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/10463615_10203329757781155_1417624536665039129_o.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/10478285_10203329760141214_7817349846728066033_o.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/10481352_10203329758741179_5663717865763476680_o.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/10494927_10203329766461372_3328827968173837844_o.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/10498301_10203329762221266_4138858298586982239_o.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/12195904_10205065748784682_750514524398623954_n.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/2014-02-20%2010.05.51.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/2014-02-20%2011.26.21.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/2014-02-20%2015.21.35.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/2014-02-25%2015.03.35.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/2014-03-14%2012.19.02%20HDR.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/2014-03-28%2012.18.46.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/2014-03-28%2016.51.40.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/2014-04-01%2011.38.03.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/2014-04-08%2015.59.00.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/2014-04-08%2015.59.09.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/2014-04-08%2015.59.36.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/2014-04-08%2015.59.58.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/2014-04-08%2016.00.01.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/2014-04-09%2016.17.48%20HDR.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/2014-04-09%2016.17.53.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/2014-04-09%2016.17.58.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/2014-04-09%2017.39.39.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/2014-04-09%2017.39.46.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/2014-04-09%2018.08.01.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/2014-04-10%2014.00.37.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/2014-04-10%2014.01.30.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/2014-04-10%2014.02.35.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/2014-04-11%2009.19.17.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/2014-04-11%2015.42.53.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/2014-04-11%2016.56.54.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/2014-04-12%2016.23.24.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/2014-04-13%2020.33.15.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/2014-04-14%2012.55.11.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/2014-04-14%2012.55.34.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/2014-04-18%2016.41.27.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/2014-04-18%2017.57.19.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/2014-04-21%2014.42.17.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/2014-04-21%2018.44.56.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/2014-04-25%2017.09.09.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/2014-04-25%2017.09.24%20HDR.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/2014-04-28%2017.04.50.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/2014-04-29%2010.00.52.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/2014-05-01%2016.13.56.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/2014-05-07%2013.43.07.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/2014-05-07%2018.48.41.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/2014-05-09%2012.30.29.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/2014-05-09%2012.54.32.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/2014-05-09%2014.18.50.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/2014-05-09%2014.18.55.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/2014-05-09%2014.19.00%20HDR.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/2014-05-12%2016.01.36.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/2014-05-13%2009.33.15.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/2014-05-16%2012.57.53.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/2014-05-16%2014.07.51%20(1).jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/2014-05-16%2014.07.51.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/Copy%20of%20DSC_0091.JPG"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/Copy%20of%20DSC_0125.JPG"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/Copy%20of%20DSC_0139.JPG"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/Copy%20of%20DSC_0141.JPG"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/Copy%20of%20DSC_0190.JPG"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/Copy%20of%20Slack%20for%20iOS%20Upload-12.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/Copy%20of%20Slack%20for%20iOS%20Upload-14.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/Copy%20of%20Slack%20for%20iOS%20Upload-16.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/Copy%20of%20Slack%20for%20iOS%20Upload-18.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/Copy%20of%20Slack%20for%20iOS%20Upload-20.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/Copy%20of%20Slack%20for%20iOS%20Upload-22.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/Copy%20of%20Slack%20for%20iOS%20Upload-24.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/Copy%20of%20Slack%20for%20iOS%20Upload-27.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/Copy%20of%20Slack%20for%20iOS%20Upload-34.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/Copy%20of%20Slack%20for%20iOS%20Upload-6.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/Copy%20of%20Slack%20for%20iOS%20Upload-8.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/DSC_0002.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/DSC_0003%20(1).jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/DSC_0003.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/DSC_0006.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/DSC_0007.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/DSC_0008.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/DSC_0009.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/DSC_0011.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/DSC_0015.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/DSC_0016.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/DSC_0017.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/DSC_0019.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/DSC_0020%20(1).jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/DSC_0020.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/DSC_0023%20(1).jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/DSC_0023.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/DSC_0024.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/DSC_0025.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/DSC_0026.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/DSC_0028.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/DSC_0029.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/DSC_0031.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/DSC_0036.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/DSC_0040.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/DSC_0044.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/DSC_0045.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/DSC_0055.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/DSC_0058.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/DSC_0065.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/DSC_0075.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/DSC_0078.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/DSC_0099.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/DSC_0100.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/DSC_0101.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/DSC_0110.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/DSC_0117.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/DSC_0118.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/DSC_0120.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/DSC_0121.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/DSC_0129.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/DSC_0136.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/DSC_0139.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/DSC_0141.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/DSC_0149.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/DSC_0156.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/DSC_0157.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/DSC_0158.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/DSC_0161.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/DSC_0170.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/DSC_0171.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/DSC_0172.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/DSC_0282.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/DSC_0285.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/DSC_0286.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/DSC_0304.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/DSC_0307.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/DSC_0310.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/DSC_0409.JPG"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/DSC_0437.JPG"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_0001.JPG"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_0034.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_0162.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_0216.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_0225.JPG"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_0238.JPG"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_0268.JPG"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_0298.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_0302.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_0303.JPG"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_0310.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_0317.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_0318.JPG"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_0336.JPG"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_0426.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_0448.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_0487.JPG"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_0512.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_0513.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_0514%20(1).jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_0514.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_0515.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_0516%20(1).jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_0516.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_0520.JPG"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_0530.JPG"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_0545.JPG"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_0549.JPG"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_0555.JPG"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_0557.JPG"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_0559.JPG"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_0562.JPG"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_0564.JPG"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_0640.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_0644.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_0651.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_0656.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_0658.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_0662.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_0663.JPG"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_0664.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_0665.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_0666.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_0667.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_0668.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_0669.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_0670.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_0671.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_0672.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_0673.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_0674.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_0675.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_0676.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_0677.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_0678.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_0679.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_0683.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_0703.JPG"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_0761.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_0773.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_0774.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_0779.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_0783.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_0788.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_0796.JPG"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_0807.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_0828.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_0840.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_0841.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_0854.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_0871.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_0880.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_0881.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_0967.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_0997.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_1023.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_1050.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_1116.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_1118.JPG"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_1128.JPG"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_1168.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_1219.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_1268.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_1274.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_1326.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_1334.JPG"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_1337.JPG"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_1378.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_1384.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_1415.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_1420.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_1421.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_1422.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_1435.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_1438.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_1439.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_1445.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_1466.JPG"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_1480.JPG"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_1499.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_1500.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_1501.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_1503.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_1504.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_1505.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_1506.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_1507.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_1509.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_1511.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_1514.JPG"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_1515.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_1523.JPG"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_1546.JPG"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_1617.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_1631.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_1651.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_1652.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_1674.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_1677.JPG"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_1700.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_1701.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_1717.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_1826.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_1852.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_1854.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_1885.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_1985.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_2004.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_2009.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_2039.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_2047.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_2052.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_2085.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_2102.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_2147.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_2165.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_2180.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_2181.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_2183.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_2211.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_2212.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_2242.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_2256.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_2305.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_2317.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_2318.JPG"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_2325.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_2336.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_2343.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_2354.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_2422.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_2423.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_3606.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_3929.JPG"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_3971.JPG"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_3975.JPG"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/IMG_3987.JPG"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/PANO_20140507_185300.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/dsc_0136-e1440539958129-960x485.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/photo%202-3.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/photo%203-1.jpg"
         }, {src: "https://raw.githubusercontent.com/dominathan/Photos-for-Calvin/master/westbrook.jpg"
         }
       ];


      $scope.randomPhoto = function() {
        return $scope.photos[Math.floor(Math.random()*$scope.photos.length)].src
      }

  })



}());
